// Code generated by cmd/syncdocs. DO NOT EDIT.

package site

// Revisions of the synced documentation.
const (
	goesmRef = "v0.0.1-beta.0"                            // github.com/goesm-dev/goesm v0.0.1-beta.0
	gosfcRef = "60ac235c2d5339028c79d300a40265e0c3d14ec6" // github.com/goesm-dev/gosfc v0.0.0-20261004190310-60ac235c2d53
)
