// Code generated by cmd/syncdocs. DO NOT EDIT.

package site

// Revisions of the synced documentation.
const (
	goesmRef = "v0.0.1-beta.1"                            // github.com/goesm-dev/goesm v0.0.1-beta.1
	gosfcRef = "142c5474d5837c079a04899ecd51906f70f96c40" // github.com/goesm-dev/gosfc v0.0.0-20261005085226-142c5474d583
)
